# Generated by Django 3.1 on 2023-05-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='userid')),
                ('username', models.CharField(max_length=20, verbose_name='user name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_infos',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('number_id', models.CharField(max_length=30, verbose_name='num_id')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('content', models.TextField(verbose_name='意见信息')),
                ('flag', models.IntegerField(choices=[(0, '匿名'), (1, '不匿名')], default=0)),
                ('show', models.IntegerField(choices=[(0, '不进行展示'), (1, '进行展示')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'optinions',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(upload_to='%Y%m%d', verbose_name='图片')),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opinion')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
